CREATE TABLE TBL_SPITTER (
  ID        NUMBER(30, 0) PRIMARY KEY NOT NULL,
  USERNAME  VARCHAR2(30)              NOT NULL,
  PASSWORD  VARCHAR2(50)              NOT NULL,
  FIRSTNAME VARCHAR2(20)              NOT NULL,
  LASTNAME  VARCHAR2(20)              NOT NULL
);