INSERT INTO TBL_SPITTER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES (1, 'jbauer', '24hours', 'Jack', 'Bauer');
INSERT INTO TBL_SPITTER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES (2, 'jbauer1', '24hours', 'Jack1', 'Bauer1');
INSERT INTO TBL_SPITTER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES (3, 'jbauer2', '24hours', 'Jack2', 'Bauer2');
INSERT INTO TBL_SPITTER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES (4, 'jbauer3', '24hours', 'Jack3', 'jbauer3');
INSERT INTO TBL_SPITTER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES (5, 'jbauer4', '24hours', 'jbauer4', 'Bauer4');